### ISSUE TITLE
Please cut a tagged release for this

### ISSUE THREAD

**Issue by keithamus** [mschneider82/keylight-systray#1]
Hey @mschneider82!

This is great work! I've started using this tool already, and it works excellently for me! I submitted [keylight-control to AUR](https://aur.archlinux.org/packages/keylight-control/) which worked really well. I'm having a little more difficulty with keylight-systray because there's no git-tag!

Could you please add an initial release tag for this repository? Thanks

**Comment by keithamus** [comment]
I've published it using the git hash: https://aur.archlinux.org/packages/keylight-systray/. A release version would be really nice though :smile_cat:

**Comment by mschneider82** [comment]
ok thanks! i tagged v0.1.0 (same version as keylight-control)

**Comment by keithamus** [comment]
Thanks! Please let me know your AUR username if you have one, and I can grant you maintainer rights on these packages!

I'll close this as it's now resolved :tada:

**Comment by mschneider82** [comment]
btw I use ubuntu ;-) so i dont have an AUR account
since github is linked, its easy submit issues here. 
my both elgato tools are running fine here since month, but i could expect some gui layouting issues when someone has more than 2 or 3 keylights..
